// <auto-generated />
using System;
using HappyLetters.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyLetters.Migrations
{
    [DbContext(typeof(RiddlesContext))]
    [Migration("20221213135527_Refactor")]
    partial class Refactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("HappyLetters.Entities.LetterRiddle", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("LetterRiddles");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("a3429643-fc11-4ccf-88dd-c061d50b75ba"),
                            Content = "A",
                            Solution = "A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
