// <auto-generated />
using System;
using HappyLetters.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyLetters.Migrations
{
    [DbContext(typeof(RiddlesContext))]
    [Migration("20221213134836_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("HappyLetters.Entities.LetterRiddle", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("LetterRiddles");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("fa5283ef-c8bb-472d-ba47-6e87242ea727"),
                            Answer = "A",
                            Content = "A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
